name = "suhail-travel-api"
main = "suhail-api-worker.js"
compatibility_date = "2026-09-10"

[observability]
enabled = true

[secrets]
required = ["DUFFEL_TOKEN"]
[[mtls_certificates]]
binding = "HOTELBEDS_MTLS"
certificate_id = "6ab0007f-bc4b-40d3-a4f8-65e4af5c3aff"
